altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4a2b31bb-bf1e-4623-8473-8d66664769a6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T20:26:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bf5fc736-5efa-4347-a96a-c44d8d5716ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T20:28:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9a1a5703-8b07-4afa-9239-840488a3a35a # PDF
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 229934af-d758-46a6-a3c9-aa93b2bba771
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: adbfe100-0d32-4bc3-a166-8b0fd58a5660
        userCondition: null
fs: pdf
handle: pdf
name: PDF
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: pdf
transformSubpath: ''
