columnSuffix: null
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  createButtonLabel: 'neues Element'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 3afe3600-f29a-4409-9b22-764f71a881c5 # Rich Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ca82ce19-1d0f-494a-b0e9-79eab0ba3665 # CTA
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 9f8d5177-949f-420b-be9a-2f552d514a68 # Images
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 26db054c-db10-4316-b753-0544f54f6710 # Related Entries
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2a3500d7-9902-4400-9a6d-7564e565cd9d # Feature List
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7601d3fa-9b2e-43fb-9b7a-d31bdc9d1e90 # Tabelle
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 36580dc2-b3e7-4432-9060-5b6939837f41 # iFrame
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 3823dd93-81bc-47aa-8fd9-c5de01cff3a6 # iFrame Sound
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2b8b4781-f0a4-4e21-9e66-2dc6b287f563 # Gif
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 32ac4396-9f07-4795-9ef4-00a03cf4d899 # PDF
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - da131c94-f785-4729-ba1e-d27ff138f6a0 # 2 Spalten RichText
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
