columnSuffix: null
handle: pageBackgroundColor
instructions: null
name: 'Page Background-Color'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
