color: orange
fieldLayouts:
  54617db6-5d0b-4f50-b5ac-5e5dd6b296e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-28T12:45:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98f30c8c-cd0c-4f1d-90f9-81e2ffabc798
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-28T12:46:42+00:00'
            elementCondition: null
            fieldUid: bdf32217-a781-41f4-8a9d-ba623b04e90a # Image Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57da34d4-a05e-413c-97b1-71f703402198
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-28T12:45:33+00:00'
            elementCondition: null
            fieldUid: b3f3c321-3167-4f74-8f3e-a3a6a7b75f96 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bec645d2-84ec-4940-a539-f88f6585b670
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-28T12:45:33+00:00'
            elementCondition: null
            fieldUid: e2f3b30c-2b00-465f-b42b-5b8e8e0ab107 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: Inhalt
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f050d24a-d6ff-4d3e-ae0f-4df0a18c22b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-28T12:45:33+00:00'
            elementCondition: null
            fieldUid: f53223cc-170a-472c-9561-2f22df16bc96 # Longform Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dd551a3-4a9a-438f-95e1-c49196d34862
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9eac994a-e74a-43ce-b215-cd3dffcf31bc
        userCondition: null
handle: blog
hasTitleField: true
icon: ''
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
