color: null
description: null
fieldLayouts:
  7fd73d1e-3e28-4ae8-a944-395844ce34be:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T05:38:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf8e2c11-d6f3-400a-ad76-6b285ec8e3d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T10:17:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e57dd80e-fbbb-45c8-9086-b5a5368c2429 # Image Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 777e063b-d65b-45bf-8237-d4f16b07e0ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T09:23:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5ba7464f-2767-483b-8cdb-a89f28b8c6cf # Image Teaser
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3329739-0a2d-4794-b037-1525f3a474ee
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-10T19:14:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e49c153e-aba5-4b59-ab1f-da3340c757d2 # Page Background-Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b83f055-2677-4bda-afab-7103b2703f82
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-10T05:38:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6a8579a0-7f72-41c9-9a9b-4d6d4f5ad746 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56483036-f1a7-489f-8a87-741b7f587725
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c529e12-49bc-4f9b-9453-276ad53712c0
        userCondition: null
handle: landingpage
hasTitleField: true
icon: null
name: Landingpage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
