color: yellow
description: null
fieldLayouts:
  0db6d68d-f684-44f6-a77a-e6fde8673b31:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T20:27:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91e5edf3-3cb5-4c56-a609-d522bf466d24
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T20:29:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9a1a5703-8b07-4afa-9239-840488a3a35a # PDF
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be68df9b-34f6-453b-866d-dd0452b4c22f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4e9060e-75fe-4362-baae-e1db87bc4885
        userCondition: null
handle: pdf
hasTitleField: true
icon: file-pdf
name: PDF
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
